name: Build Spade UF2
on: # This workflow should run on...
  push: # a push...
    branches: # to one of these branches:
      - 'main'
      - 'add-ci' # TEMP for testing
  workflow_dispatch: # or when manually triggered

defaults:
  run:
    shell: 'bash'

jobs:
  build-uf2:
      runs-on: 'ubuntu-latest' # Run on the latest stable Ubuntu version
      steps:
      - name: 'Clone Spade repo'
        run: |
          cd ~/
          git clone https://github.com/hackclub/sprig.git sprig/
          
      - name: 'Build Script'
        run: cd ~/sprig/firmware/spade && ../../scripts/gardenshed/build.sh
      
      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'spade.uf2'
          path: '~/sprig/firmware/spade/spade.uf2'
          if-no-files-found: error
